version: '3.1'
services:
  postgresql:
    image: postgres
    restart: always
    env_file:
      - db.env 
    volumes:
      - db-data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
  vaccinex_api:
    build: .
    restart: always
    ports:
        - 8000:8000
    depends_on:
        - postgresql
volumes:
    db-data:
